"""delete unique on user_id in posts table

Revision ID: ac0733f10e6b
Revises: 1dfa7ad53391
Create Date: 2025-07-27 20:50:31.125735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0733f10e6b'
down_revision: Union[str, Sequence[str], None] = '1dfa7ad53391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_user_id_key'), 'posts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('posts_user_id_key'), 'posts', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
